### ISSUE TITLE
Missing Manual link for Chat

### ISSUE THREAD

**Issue by shmup** [scandum/tintin#111]
https://tintin.mudhalla.net/manual/

Currently:

```html
<a href="characters.php">Characters</a><br>
Chat<br>
<a href="_class.php">Class</a><br>
```

Should be:
```html
<a href="characters.php">Characters</a><br>
<a href="chat.php">Chat</a><br>
<a href="_class.php">Class</a><br>

**Comment by scandum** [comment]
Works for me, the only way to reproduce that on my end is to go to the actual https://tintin.mudhalla.net/manual/chat.php page.

**Comment by shmup** [comment]
Yeah.. you're totally right :blush: 

Oops.. lol. Good call.
