### ISSUE TITLE
#split looks weird in #action

### ISSUE THREAD

**Issue by dzpao** [scandum/tintin#113]
I found a trivial bug, if I use `#split` in `#action`, I find that the line of text that causes the trigger will appear on the input line, which often messes up my screen.
like this:

![image](https://user-images.githubusercontent.com/52447680/185730140-b3ad5678-8263-42ad-a343-b4b19865e0a5.png)

This is the test script:

```
#split;
#session cf carrionfields.net 4449;
#action {^By what name do you wish to be mourned? } {
    #nop has bug;
    #split;
    #nop has not bug;
    #nop #delay 0 #split;
};
```

If I use `#delay 0 #split` then I don't get this.

**Comment by scandum** [comment]
Fixing it like that can result in screen flicker when a lot of data is received. I updated the beta with another fix that checks for FLAG_READMUD in split.c.
