### ISSUE TITLE
CJK Character Display BUG

### ISSUE THREAD

**Issue by flw-cn** [scandum/tintin#14]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/5546718/95944498-e5118000-0e1a-11eb-8822-d4aa3a1014c9.png">

As you can see above, there is not enough space left at the right end of that line to display a full character, but tintin doesn't seem to know that and still tries to display the next character 未 or 也, so iTerm2 displays it on the next line, and after that, tintin creates a new line, so that there is a single character all by itself.

I'm optimistically guessing that this is due to the width calculation.

**Comment by scandum** [comment]
Thanks, should be fixed in the beta version.
