### ISSUE TITLE
Debug telnet lies with NAWS and split

### ISSUE THREAD

**Issue by nyankers** [scandum/tintin#140]
When `#config {debug telnet} {on}` is enabled, and NAWS messages are being sent, it echos to the user the window size ignoring things like `#split`.

The actual sizes sent subtract the area taken up by `#split`.

So for example, if the window size is 151x40 prior to running `#split`, then after typing `#split`, it'll still print `SENT IAC SB NAWS 0 151 0 40` though the server will actually receive `IAC SB NAWS 0 151 0 38 IAC SE`.

The actual value sent seems reasonable to me, the only issue is that the debugging echo doesn't match it.

**Comment by scandum** [comment]
Should be fixed in 2.02.30.
