### ISSUE TITLE
#echo doesn't work right in {SEND OUTPUT} event. (TinTin++ 2.02.20)

### ISSUE THREAD

**Issue by msocorcim** [scandum/tintin#144]
#event {SEND OUTPUT}
#EVENT {SEND OUTPUT}
{
    #format {lineout} {%p} {%0};
    #echo {<199>SENT:<099> %s} {$lineout} ;
    #unvariable {lineout}
}
/* expected behavior: */
look
SENT: look

#EVENT {SEND OUTPUT}
{
    #format {lineout} {%p} {%0};
    #echo {<199>SENT:<099> %s <199>MORE TEXT<099>} {$lineout} ;
    #unvariable {lineout}
}

/* unexpected behavior: */
look
 MORE TEXT
/* expected behavior would have been: */
look
SENT: look MORE TEXT

/* outside of the event, #echo works as expected */
#echo {<199>SENT:<099> %s <199>MORE TEXT<099>} {testing output}
SENT: testing output MORE TEXT

**Comment by scandum** [comment]
It's somewhat explained in `#help event`
```
SEND OUTPUT            %0 raw text %1 size
```
%0 contains the raw text, which includes the `\r\n` newline sequence.

One thing you could do is:
```
#EVENT {SEND OUTPUT}
{
    #line convert#format {lineout} {%p} {%0};
    #replace lineout {\r\n} {};
    #echo {<199>SENT:<099> %s <199>MORE TEXT<099>} {$lineout} ;
    #unvariable {lineout}
}
```
In the latest beta however `#format %p` will strip trailing newlines. So if you were expecting %p to strip new lines, that has been fixed.
