### ISSUE TITLE
Starting with user interface (-g) crashes

### ISSUE THREAD

**Issue by rigrig** [scandum/tintin#155]
Running `tt++ -g` crashes:
After printing the welcome banner, it shows `free(): double free detected in tcache 2` <details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/2941436/210629307-3d43d86a-c709-431e-b9ce-fba7d74449a9.png)

</details>

and exits with
```
DEBUG_STACK[000] [000] = command(%p,%p,%p,...)

syserr_fatal(crashed) 
```

TinTin++ version: `2.02.30` (`master`, compiled from source)
It works fine with the previous commit (`2.02.21b`)

Running `tt++ ~/.tintin/gui.tin` does work, showing the world chooser.

**Comment by scandum** [comment]
Thanks for letting me know, annoying how some things work with Cygwin but not Ubuntu.

**Comment by scandum** [comment]
Should be fixed in the beta. https://mudhalla.net/tintin-beta.tar.gz

**Comment by rigrig** [comment]
Thanks, that was fast!
Tried it, and it no longer crashes. 🎉

**Comment by prool** [comment]
Hello!

Report: Debian 11. tintin version 2.02.30 has crashed with flag -g

tintin beta - no crashed

Remark: graphic mode (-g flag) is very nice!

Prool
