### ISSUE TITLE
Not super clear that the tintin++ apt-get package installs tt++

### ISSUE THREAD

**Issue by MihaiOnSoftware** [scandum/tintin#161]
Thanks for making this awesome tool!

Currently when installing tintin++ from apt-get the package is named tintin++ but the actual executable and man pages are for tt++. This can be very confusing to someone using it for the first time, I ended up having to look into the file list of the package to see what exactly I should be looking for. Options that might solve this are:
- The package is renamed to tt++
- A post-install script informs the user of the name tt++
- tt++ is renamed to tintin++ and users can alias it as needed
- an alias is created by default
- there are two executables: tt++ and tintin++ but the man page stays as tintin++
- Documentation is updated to make it clear that the executable is tt++ (low effort but will likely still lead to confusion)

There are definitely other options I'm not thinking of as well and this is possibly a minor issue but it does require some knowledge of Linux systems to figure it out so for some less tech savvy Windows users it might be a blocker.

Anyway, thanks for the amazing work!

**Comment by scandum** [comment]
Thanks.

I don't maintain any of the packages, so I don't have much control over that aspect.

I'll see if I can add a note in the installation section of the website to package maintainers.

Name: `tintin++`, `tintin`, or `tintinpp`

Category: Games, Misc, Util, Net, or Internet

License: GPL3

Summary: TinTin++, aka tt++, is an extensible console MUD client

Homepage link: https://tintin.mudhalla.net

Repository link: https://github.com/scandum/tintin

Download link: https://github.com/scandum/tintin/releases/

At least I assume the executable is consistently named tt++, so perhaps a post-install script informing the user the executable and man page are tt++?
