### ISSUE TITLE
[REQUEST] Adding a `#info` option such as `#info output save` can be used to get the output text in raw format when the action is triggered.

### ISSUE THREAD

**Issue by dzpao** [scandum/tintin#166]
Adding a `#info` option such as `#info output save` can be used to get the output text in raw format when the action is triggered.

One problem we often encounter when writing bots is that some text is so colorful that it is difficult to write a color trigger, but it is easy to write a plain text trigger. But we want to use that line of text for some processing (such as sorting logs), so it would be helpful to have a way to get the text in its raw format.

I have a little patch here that does this, maybe it doesn't do it right, but I think it at least illustrates what I want.

```C
diff --git a/src/data.c b/src/data.c
index 5045079..ff72a46 100644
--- a/src/data.c
+++ b/src/data.c
@@ -1641,6 +1641,24 @@ DO_COMMAND(do_info)
 				}
 				break;
 
+			case CTRL_O:
+				if (is_abbrev(arg1, "OUTPUT"))
+				{
+					if (is_abbrev(arg2, "SAVE"))
+					{
+						set_nest_node_ses(ses, "info[OUTPUT]", "{BUFFER}{%s}", gtd->mud_output_buf);
+						add_nest_node_ses(ses, "info[OUTPUT]", "{BUFLEN}{%d}", gtd->mud_output_len);
+						add_nest_node_ses(ses, "info[OUTPUT]", "{LINE}{%s}", gtd->mud_output_line);
+                    }
+					else
+					{
+						tintin_printf2(ses, "#INFO OUTPUT: BUFFER: %s", gtd->mud_output_buf);
+						tintin_printf2(ses, "#INFO OUTPUT: BUFLEN: %d", gtd->mud_output_len);
+						tintin_printf2(ses, "#INFO OUTPUT: LINE: %s", gtd->mud_output_line);
+					}
+                }
+                break;
+
 			case CTRL_S:
 				if (is_abbrev(arg1, "SESSION"))
 				{
diff --git a/src/net.c b/src/net.c
index be1341b..74ec471 100644
--- a/src/net.c
+++ b/src/net.c
@@ -557,6 +557,7 @@ void readmud(struct session *ses)
 
 		if (ses->check_output)
 		{
+			gtd->mud_output_line = line;
 			process_more_output(ses, line, next_line == NULL);
 
 			continue;
@@ -570,6 +571,7 @@ void readmud(struct session *ses)
 		{
 			strcpy(linebuf, line);
 		}
+		gtd->mud_output_line = line;
 		process_mud_output(ses, linebuf, next_line == NULL);
 	}
 	DEL_BIT(cts->flags, SES_FLAG_READMUD);
diff --git a/src/tintin.h b/src/tintin.h
index 60933ec..3402daf 100644
--- a/src/tintin.h
+++ b/src/tintin.h
@@ -1133,6 +1133,7 @@ struct tintin_data
 	char                  * mud_output_buf;
 	int                     mud_output_max;
 	int                     mud_output_len;
+	char                  * mud_output_line;
 	unsigned char         * mccp_buf;
 	int                     mccp_len;
 	char                    macro_buf[BUFFER_SIZE];

```

**Comment by scandum** [comment]
Excellent suggestions. I've added it to my todo list. I'll try to add it to the beta within a week. I'll indeed do a few things slightly differently.

**Comment by dzpao** [comment]
Looking forward to your masterpiece.

I plan to use this feature to cache some game texts and view them again later. Although they may not always be available from the server, I can always view them as long as I keep a copy of the cache locally.

**Comment by scandum** [comment]
I'm not sure about the utility, other than for debugging, but LINE, STRBUF (color codes stripped) and STRLEN can be accessed in an action. The RAWBUF gets mangled by tintin while breaking up the output into single lines. You can access it with the RECEIVED OUTPUT event.
```
#info output
#INFO OUTPUT: RAWBUF:
#INFO OUTPUT: RAWLEN: 0
#INFO OUTPUT: STRBUF:
#INFO OUTPUT: STRLEN: 0
#INFO OUTPUT: LINE:
```
I just noticed the RAWLEN wasn't properly set in yesterday's release, but I just fixed that in the beta.

I'm not convinced this is a useful addition, but perhaps it could be with some further improvements.
