### ISSUE TITLE
#map list crashes since 2.02.30

### ISSUE THREAD

**Issue by fabshine** [scandum/tintin#167]
Hi,

Since I upgraded to 2.02.30, map function 

`#map list {roomnote} <anything_to_search>`

doesn't work properly anymore, and the client crashes...
Working under an up-to-date AWS Amazon linux vm.

I tried #CONFIG {VERBOSE} HAS BEEN SET TO {ON}, but I don't get any message before tintin++ stop/crash.

**Comment by scandum** [comment]
Hiyas,

This might be something that has been fixed in the beta.

https://mudhalla.net/tintin-beta.tar.gz

**Comment by fabshine** [comment]
> Hiyas,
> 
> This might be something that has been fixed in the beta.
> 
> https://mudhalla.net/tintin-beta.tar.gz

Thank you, it looks indeed like it has been fixed.
