### ISSUE TITLE
#cursor get and curly braces

### ISSUE THREAD

**Issue by nyankers** [scandum/tintin#169]
Using `#CURSOR GET` has some odd behavior with curly braces. It basically seems like it's not escaping them, so when the variable is later used, they're treated as code braces rather than characters.

For example:
```
#macro {X} {
	#cursor {get} {t};
	#if {{$t} == {}} {
		#echo {nothing};
	};
	#else {
		#echo {something: %s} {$t};
	};
}
```

This throw error messages if the buffer contains `{` but will work if it contains other stuff, such as `blah{`.

The error message: `#ERROR: GET BRACED ARGUMENT: UNMATCHED BRACE.`

However, using it as an index to another variable (whether using `$` or `&`), even `blah{` will spam the above error message:
```
#var {lookup} {{a}{alpha}}
#macro {Z} {
	#cursor {get} {t};
	#echo {%s} {${lookup[$t]}};
}
```

**Comment by scandum** [comment]
Thanks, I added it to my todo list. Thought I had fixed it a while ago, but apparently not.

**Comment by scandum** [comment]
Should be fixed in yesterday's release. It goes through the generic escaping routine now, so `;` and some other characters are escaped as well.
