### ISSUE TITLE
Bad printfs

### ISSUE THREAD

**Issue by nyankers** [scandum/tintin#170]
I found a couple bad printfs.

`mapper.c:7143` is passing an integer to a `%8.3f`, causing an issue whenever this code was reached, I changed `-1` to `-1.0` on my local to fix it:
```
tintin_printf2(ses, "vnum: %5d  dist: %8.3f  x: %4s  y: %4s  z: %4s  name: %s", room->vnum, -1, "?", "?", "?", room->name);
```

`mapper.c:3422` has more arguments than tokens, I haven't tested this one but found it while looking into the above issue:
```
cat_sprintf(buf, "%s%5.1f", ses->map->color[MAP_COLOR_USER], room->length, ses->map->color[MAP_COLOR_EXIT]);
```

**Comment by scandum** [comment]
Thanks, both issues should be fixed in the beta version now: https://mudhalla.net/tintin-beta.tar.gz
