### ISSUE TITLE
Modular arithmetic + parentheses gives wrong answer

### ISSUE THREAD

**Issue by ethorondil** [scandum/tintin#18]
```
#math {a} {(1+1)%10}
#MATH: VARIABLE {a} HAS BEEN SET TO {0}.
```

Obviously, (1 + 1)%10 is 2, not 0.

This is a regression in 2.02.05, I believe.

**Comment by scandum** [comment]
Thanks, fixed the problem in the beta available at mudhalla.net/tintin-beta.tar.gz.
