### ISSUE TITLE
Screen reader is not immediately speaking new content printed onto the screen

### ISSUE THREAD

**Issue by LittleStar-VIP** [scandum/tintin#183]
# problem I am facing

The problem that I am facing, is sometimes when new line are printed to the screen, the screen reader will read some older lines before reading those new lines
1. Currently there are line 1 to line 10 on the screen
2. I type e to go east
3. instead of start speaking what is newly printed onto the screen (i.e. what is the room that after going east), my screen reader will speak something from line 1 to line 10
4. it is not always speaking everything from line 1 to line 10, some times is only one of the line, sometimes is a few lines
5. after speaking those old lines, my screen reader will start speaking those new lines printed on the screen

#version and related info
TinTin++ 2.02.31
nvda 2023.1
I am using the installed version of tintin on Windows 10

**Comment by scandum** [comment]
There are three things you can try.

1. #config color off
2. #split
3. #config packet_patch 0.5

It's hard for me to tell whether this is a bug in tintin, or a bug in nvda. You can also use `#config screen_reader on` to make tintin more screen reader friendly.

**Comment by LittleStar-VIP** [comment]
Thank you, based on your suggestions, I have adjusted my configuration, and let me post all the custom configurations that I have made.

#nop General configuration
#show {\e>}
#config buffer_size 1000000
#CONFIG {SPEEDWALK} {ON}
#config screen on
#config {VERBOSE} {ON}
#config {compact} {ON}
#CONFIG {LOG} {PLAIN}
#CONFIG           {WORDWRAP}  {ON}
#CONFIG {CONNECT RETRY} {300}
#config color {off}
#split
#config packet_patch 0.5


#screen fullscreen {ON}

#nop #debug all log


#read {AAMiningDeposit.tin}

#read {AA.tin}

**Comment by LittleStar-VIP** [comment]
Hmm, I am still experiencing similar problem after applying the above configuration

**Comment by scandum** [comment]
Another thing worth trying is using the WinTin++ (Windows Console) shortcut from the Windows start menu. That shortcut will launch tintin++ with the default windows terminal instead of the mintty terminal.

I suspect the problem is with either windows O.S. or nvda.

I forgot to ask, will it consistently mess up when walking into the same room, or is it random?

**Comment by LittleStar-VIP** [comment]
Hello, thank you again.
I try to press windows start menu, enter wintin and launch wintin++ from the start menu,
But it seems that either run the shortcut from the desktop or run from the start menu, both the applications are the same?

Window Class:
mintty
Process Name:
mintty.exe

Well the strange behaviors does not restricted to walking into a new room, it may happen anytime when I issue a command and new lines are printed onto the screen
Sometimes it is strange that it speak a few lines that are newly pritned onti the screen (line 11 - line 13 for example) and it goes back to speak from line 1 to line 10 again, and then speak line 14 onwards.

**Comment by scandum** [comment]
You will likely have to enter `wintin++ (w` to narrow it down to the right shortcut.

**Comment by LittleStar-VIP** [comment]
O thank you, it is a different process now

Window Class:
ConsoleWindowClass
Process Name:
tt++.exe

It seems that things are better now here, let me observe how does it behave in the coming days.

**Comment by LittleStar-VIP** [comment]
Sorry just come across another issue, I have enabled use ctrl x c v to paste in windows console
but it seems that I cannot paste using ctrl v in this wintintin++ windows console

**Comment by LittleStar-VIP** [comment]
I have used the windows console for a few days and the problems of randomly reporting old messages by nvda hasn't been noticed here.

**Comment by scandum** [comment]
About the only thing you could do would be to run tintin++ inside Cygwin or WSL.

This would require for you to learn how to use the Linux console however, worth learning, but perhaps more than you're willing to invest.

**Comment by LittleStar-VIP** [comment]
> About the only thing you could do would be to run tintin++ inside Cygwin or WSL.
> 
> This would require for you to learn how to use the Linux console however, worth learning, but perhaps more than you're willing to invest.

Ok, understood, thanks.

**Comment by LittleStar-VIP** [comment]
Sorry not sure if it is ok to ask the question here, please let me know if the correct place to post this,
I don't quite understand what does this line of instruction is asking me to do 
''Edit .bashrc and add 'cd' at the end of the file to automatically switch to your home directory when using Mintty WLC Bridge.''''

**Comment by LittleStar-VIP** [comment]
> .bashrc is the name of a file in the WSL user home directory.

Hello, I located the possible file you mentioned,
C:\Users\LittleStar\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc\LocalState\rootfs\home\littlestar\.bashrc
So I have to use my text editor to open this file, and add the following line at the end of the file?
cd C:\Users\LittleStar
 


> In your case, you would want to use the default Windows Console instead of installing Mintty.

What I have already done is:
- Once Ubuntu is up and running use 'sudo apt-get update' and 'sudo apt-get install tintin++' to install TinTin++.
- Download and use the Mintty WSL Bridge installer to use Mintty as your WSL Terminal instead of the Windows 10 Bash console.

So do you mean I don't have to install the Mintty WSL Bridge?
But I cannot start tintin++ directly from the wsl console by typing 'tintin++'

**Comment by scandum** [comment]
You would have to use your text editor to editing the .bashrc file, though I'm not sure if it's necessary to edit .bashrc if you use the default console.

Also keep in mind that WSL files should be edited with a Linux editor to avoid file corruption. So you could try using `nano .bashrc` to use the nano editor. You can press ctrl-g for help within nano.

To start tintin++ you would type `tt++`.

**Comment by LittleStar-VIP** [comment]
Oh thank you thank you, I was able to run the tt++ using wsl.
Probably the last question, the wsl tintin++ is probably loading the main.tin from a different directory,
where should I paste the old main.tin in order to let wsl tt++ to read my old main.tin file?
thanks.

**Comment by LittleStar-VIP** [comment]
Thank you  very very much, I was able to run tt++ with main.tin under wsl.

**Comment by LittleStar-VIP** [comment]
Using this command can run tt++ in wsl based on my original main.tin command.
wsl tt++ /mnt/c/Users/LittleStar/AppData/Roaming/WinTin++/bin/main.tin

**Comment by scandum** [comment]
I hadn't thought of that, you could try the following command as well:
```
wsl cd /mnt/c/Users/LittleStar/AppData/Roaming/WinTin++/bin;./tt++.exe main.tin
```
That should let you run the wintin++ binary, which should be more up to date, and place you in the wintin directory.

**Comment by LittleStar-VIP** [comment]
> wsl cd /mnt/c/Users/LittleStar/AppData/Roaming/WinTin++/bin;./tt++.exe main.tin
> ```
> 
> That should let you run the wintin++ binary, which should be more up to date, and place you in the wintin directory.

Thank you, that works.
In that way, if I want to play audio using #run, where should the audio be placed?

**Comment by scandum** [comment]
There's a generic script at this link:

https://tintin.mudhalla.net/scripts/msp.php

For WSL it plays sounds from `c:\sounds` by default, might be .wav files only.

**Comment by LittleStar-VIP** [comment]
thank you
