### ISSUE TITLE
Seg fault with math

### ISSUE THREAD

**Issue by nyankers** [scandum/tintin#185]
Comparison operators seg fault when comparing text with a number, e.g. `#math t {{42} > 42}` or `#if {{42} >= 42} {#echo foo} {#echo bar}`

The debug stack output is as followed:

```
DEBUG_STACK[000] [000] = mainloop()
DEBUG_STACK[001] [000] = process_input(void)
DEBUG_STACK[002] [001] = script_driver(%p,%d,%p)
DEBUG_STACK[003] [001] = show_debug(%p,%p,%p)
```

**Comment by scandum** [comment]
Got this fixed in the 2.02.40 release.
