### ISSUE TITLE
should we put ; at the end of #case?

### ISSUE THREAD

**Issue by LittleStar-VIP** [scandum/tintin#186]
Hello,
I read from the manual and sample script file that at the end of each line of #case, there is no ;
but in my command file, it generate warning when #case is not ended with a ;
so actually do we have to include ; at the end of #case thank you.

**Comment by scandum** [comment]
I'm not aware of the manual stating any such things.

The `;` is used to separate two commands, so if you have two #case commands, they should be separated with one `;`.

The sixth and final #case in the example in #help case isn't followed by a `;`, but the #case statements preceding it are.

**Comment by LittleStar-VIP** [comment]
Oh thank you I know what is the problem, originally I was referencing to the sample script,
i.e.
#tick {randomsocial}
{
	#delay {1d180}
	{
		#switch {1d4}
		{
			#case {1} {cheer}
			#case {2} {greet all}
			#case {3} {smile}
			#case {4} {laugh self}
		}
	}
}
{200}

I see that there is no ; here

**Comment by scandum** [comment]
My bad, it's an error in the script and that should read:
```
 #switch {1d4}
 {
         #case {1} {cheer};
         #case {2} {greet all};
         #case {3} {smile};
         #case {4} {laugh self}
 }
```
I've got it fixed for the next release.

**Comment by LittleStar-VIP** [comment]
Thanks
