### ISSUE TITLE
When a undefined class is killed,The event "CLASS CREATED" would trigged

### ISSUE THREAD

**Issue by Dawn-Xu-helloworld** [scandum/tintin#196]
#event {CLASS CREATED} {#show trigged!};#class undefined kill
#EVENT {CLASS CREATED} HAS BEEN SET TO {#show trigged!}.
trigged!

**Comment by scandum** [comment]
Thanks, not a huge issue, but I'll add it to my list of things to fix.

**Comment by scandum** [comment]
All of the class commands create a class if it doesn't exist, but probably for the better if it errors out instead.

**Comment by scandum** [comment]
I think I got this straightened out in the 2.02.40 release, fingers crossed. :)
