### ISSUE TITLE
Request a method to get the name of the #class that is currently open.

### ISSUE THREAD

**Issue by dzpao** [scandum/tintin#198]
Request a method to get the name of the #class that is currently open. It's like #info class or #class info or something like that.

Because my robotics frameworks have gotten more complex, I often use abstractions, such as when I invented an event-driven programming framework, where I might register multiple events in a #class, and only one of those events will actually happen. Then when it happens, I want to unhook the other events. Then I might need to group the events, associate them with the #class, and then proactively cancel them when I detect a #class kill.

If I could get the calling environment that one of my aliases is being called in, such as the #class that is currently open, then I might do some wrapping to make this thing look a bit more reasonable.

Maybe I didn't express myself very clearly, but anyway, I'd like to have a way to get the #class that's currently open, even if it was opened at the previous calling layer.

**Comment by scandum** [comment]
You can use `#info session save` and grab the class from there.

It's also possible to keep track of the current open class with the CLASS ACTIVATED and DEACTIVATED events.

**Comment by dzpao** [comment]
Ok, I see that `info[SESSION][CLASS]` has the info I'm looking for, very good. thanks.
