### ISSUE TITLE
Add a tintin command #sleep

### ISSUE THREAD

**Issue by Dawn-Xu-helloworld** [scandum/tintin#20]
Add a command like #sleep {seconds} to sleep in the #foreach

**Comment by Dawn-Xu-helloworld** [comment]
note: another idea is #foreach {list}{varible}{command}{delay time(default is 0)}

**Comment by scandum** [comment]
You might as well use #path. Try:

```
#path load {#showme a;#showme b;#showme c}
#path run 0.7
```
