### ISSUE TITLE
about #draw and #button

### ISSUE THREAD

**Issue by wangwilde** [scandum/tintin#201]
#var co {20 30 30 50};
#draw box $co;
it's ok.
but 
#button $co TEST;
#ERROR: #BUTTON {$co} IS NOT A VALID SQUARE COORDINATE.

can make #button  same  as the #draw?

**Comment by scandum** [comment]
Why not. I've updated the beta with a fix: https://mudhalla.net/tintin-beta.tar.gz

**Comment by scandum** [comment]
Fixed in the 2.02.40 release.
