### ISSUE TITLE
#PORT init issue - gethostbyname error 0

### ISSUE THREAD

**Issue by sdols723** [scandum/tintin#202]
Hello!

On some MacOS systems an attempt to init port with command 

#port init p1 3001 

leads to error:

port_initialize: gethostbyname: Undefined error: 0

My iMac does not have this issue, my MacBook has. I just upgraded OS to the latest - it still exists. The same issue with at least one other person i know.

**Comment by scandum** [comment]
Are you running the latest tintin version? I can't find a reference to that error message in the current source code.

**Comment by sdols723** [comment]
I just installed with brew, however this can be a possible cause, let me reinstall and get back with new evidence.

**Comment by scandum** [comment]
I'll assume you got it straightened out. :)
