### ISSUE TITLE
backslashes have strange behavior when used as a key in table

### ISSUE THREAD

**Issue by dzpao** [scandum/tintin#206]
```
#var foo {\co\cd}; #var foo; #var bar {}; #var bar[\co\cd] {bar}; #var bar
#OK: VARIABLE {foo} HAS BEEN SET TO {\co\cd}.
#VARIABLE {foo} {\co\cd}

#OK: VARIABLE {bar} HAS BEEN SET TO {}.
#OK: VARIABLE {bar[\co\cd]} HAS BEEN SET TO {bar}.
#VARIABLE {bar}
{
    {co\cd} {bar}
}
#var foo {\\co\\cd}; #var foo; #var bar {}; #var bar[\\co\\cd] {bar}; #var bar
#OK: VARIABLE {foo} HAS BEEN SET TO {\\co\\cd}.
#VARIABLE {foo} {\\co\\cd}

#OK: VARIABLE {bar} HAS BEEN SET TO {}.
#OK: VARIABLE {bar[\\co\\cd]} HAS BEEN SET TO {bar}.
#VARIABLE {bar}
{
    {\co\\cd} {bar}
}
```

**Comment by scandum** [comment]
I'll make sure to document this in `#help variable`.

If you use `#unvariable \%*` it will only remove a variable named `%*`, instead of every variable.

Similarly, `$test[]` will report all nests, while `$test[\]` will report the nest with an empty string, if it exists.

Looks like there is an issue with using `$test[\$bla]` where it'll prevent the variable expansion of `bla`.

**Comment by scandum** [comment]
So I took a closer look, and using `\` for this purpose was a bad idea, so I changed it to `/` and the next release will give a warning.

Variables names are expected to solely exist of ascii letters, numbers, and underscores.

**Comment by scandum** [comment]
On second thought, it's likely for someone to store a directory structure in a table, so I'll use `=` for a strict equality assignment and lookup. Should cause few problems and be a bit more intuitive.

**Comment by dzpao** [comment]
I'm actually trying to store a ctrl sequence here, like the one used in #macro.

I don't understand what's going on under the hood here, but it looks like the escaping process is different for the first \co and the second \cd. It seems that table always handles only the first escape sequence correctly.
