### ISSUE TITLE
weird vt behaviour tintin++ 2.02.05

### ISSUE THREAD

**Issue by stb1973** [scandum/tintin#21]
Related tintin++ version: 2.02.05

The status line for characters names starting with Z on Lowlands mud (lolamud.net 6969) doesn't show correctly

How to reproduce
```
#sess zimo lolamud.net 6969
new
zimo
password123
password123
y
y
m
ran
hum
y
y
#cr
tact top
```
![image](https://user-images.githubusercontent.com/77576192/104844990-69204b80-58d3-11eb-92b8-abb0624208cd.png)

NOTE: confirmed to be working with 2.01.92

**Comment by scandum** [comment]
Are you using the windows console?

If so you might want to give the new wt (windows terminal) a try.

**Comment by stb1973** [comment]
The behaviour is no different using either windows console or windows terminal

**Comment by stb1973** [comment]
Using ubuntu (20.4) doesn't seem to help either

**Comment by scandum** [comment]
Windows terminal works alright for me.

Have you tried wsltty? https://github.com/mintty/wsltty

**Comment by stb1973** [comment]
I've been able to narrow it down to commit 6d606547261529f26eae056c3bc9df88da417317 introducing the issue I'm having.

This patch (commenting out a few lines) "fixes" the issue. (Can be applied to 2.02.5)
This could of course be a bug in Lowlands mud, so I checked MortalRealms (game.mortalrealms:4321) and found the same behaviour - which of course doesn't rule out it's a bug in the mud code, so I'll try to get some log.

```diff
 src/vt102.c | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/src/vt102.c b/src/vt102.c
index 2c56881..36889ce 100644
--- a/src/vt102.c
+++ b/src/vt102.c
@@ -1373,10 +1373,10 @@ int catch_vt102_codes(struct session *ses, unsigned char *str, int cplen)
 							}
 							break;
 
-						case 'Z':
-							check_all_events(ses, EVENT_FLAG_VT100, 0, 0, "VT100 DECID");
-							pop_call();
-							return len + 1;
+						//case 'Z':
+						//	check_all_events(ses, EVENT_FLAG_VT100, 0, 0, "VT100 DECID");
+						//	pop_call();
+						//	return len + 1;
 
 						default:
 							pop_call();
```

**Comment by stb1973** [comment]
[issue21.log](https://github.com/scandum/tintin/files/5831442/issue21.log)

After connecting:
```
#config log level low
#log a issue21.log
refresh
#delay {5} #log off
```

**Comment by scandum** [comment]
Regardless, the only term officially supported on Windows is mintty/wsltty.

I'm getting the vt100 malfunction using telnet as well, so it might be something introduced in a recent windows update.

**Comment by stb1973** [comment]
For me I haven't seen a platform that it does NOT occur on with tintin++ 2.02.04/2.02.05:
- Windows
    - mintty (using installed shortcut )
    - windows terminal
    - cmd
- Linux
   - Ubuntu 20.4 ( using virtualbox on Windows )

**Comment by scandum** [comment]
Odd, WinTin++ 2.02.05 (which uses mintty) works for me on Lowlands.

Just in case, you can try the tintin beta version: https://mudhalla.net/tintin-beta.tar.gz

So just to be clear, VT100 on Lowlands works when using telnet, breaks using tintin?

**Comment by stb1973** [comment]
telnet (both windows "built-in" using cmd and putty) work correctly on Lowlands, tintin++ 2.02.4 and up don't - using VT100 with a character name that starts with Z ( see screenshot and "how to reproduce" in earlier comments ). After commenting out the "VT100 DECID"-section from src/vt102.c, tintin++ works fine.

**Comment by scandum** [comment]
Doh. I apologize for being so dense.

Thanks for reporting and tracking down the cause. I've updated the beta with a fix.

You might want to update to the beta since there are other code / data combinations that might cause problems.
