### ISSUE TITLE
#draw tile gives an error when drawing {

### ISSUE THREAD

**Issue by rigrig** [scandum/tintin#218]
Even when escaped, drawing text containing a `{` gives an error:

    #draw tile 1 1 1 1 {\x7B}
    #ERROR: GET BRACED ARGUMENT: UNMATCHED BRACE.

TinTin++ version: 2.02.41 

I'm drawing a panel with chat history, so replacing all braces with something else isn't an ideal workaround when chatting about regexes ;-)

**Comment by scandum** [comment]
Thanks, I've updated the beta with a fix. Hopefully without introducing new bugs.

**Comment by rigrig** [comment]
Thanks, it works now!
