### ISSUE TITLE
I want to display special symbol characters on the screen. 

### ISSUE THREAD

**Issue by CryAngel1970** [scandum/tintin#231]
When I use special characters such as ─│┌ ┐○ →, they are not displayed on the screen or are only displayed halfway. They are symbol characters that take up 3 bytes in utf8. I installed cygwin and looked at the tintin++ source, but I don't know which part to modify.

**Comment by scandum** [comment]
They should display. Maybe experiment with a different font? Assuming you have mintty as your terminal, you should be able to right-click the title bar and access the options menu.

**Comment by CryAngel1970** [comment]
![snap00117](https://github.com/user-attachments/assets/08b32eb4-76a5-46c4-85ec-afb505cf60ac)
![snap00114](https://github.com/user-attachments/assets/4a684874-ae94-473a-9002-2c531d990403)
![snap00115](https://github.com/user-attachments/assets/33f1c143-1ae4-41ba-8588-2de13a4dac72)
![snap00116](https://github.com/user-attachments/assets/7a3dd220-a24b-48ee-b579-38182b3c513e)
There are some differences depending on the font, but
the symbol characters and the English alphabet are displayed overlapping.
The third is a screen where the symbol characters and the cursor overlap half of the symbol.
The last is a screen that enlarges the symbol and the English alphabet overlapping.
I don't think it's because of the font.
Is this also because of mintty?

**Comment by scandum** [comment]
It might be your Locale setting, which is set to C in your screenshot. May have to change that to English.

**Comment by CryAngel1970** [comment]
![snap00119](https://github.com/user-attachments/assets/65589e7f-da74-4074-b104-870c6623a581)
![snap00120](https://github.com/user-attachments/assets/05ed7226-146d-40d6-9abb-a40de8a7b92b)

The server I'm connected to is a utf8 server.
And I tested it by changing the locale setting to default, C, and ko-KR, but the result was the same. If you change the character set from utf8 to eucKR, the text will be broken. This is because the server I'm connected to is utf8.
There is no English in the character set.

**Comment by scandum** [comment]
My best guess is that this is some mintty issue. Looks like the right characters are getting printed, but not correctly. So you might have more luck raising an issue with mintty.

**Comment by CryAngel1970** [comment]
Okay, I really appreciate your quick response. Have a nice day.
