### ISSUE TITLE
The command language is automatically switched.

### ISSUE THREAD

**Issue by CryAngel1970** [scandum/tintin#232]
I compiled it in cygwin.
The command input state was initially in English. 
I pressed the key that switches the command input state to Korean and switched to Korean input mode. 
When I press Enter and try to input the command again, it switches to English input state.
Every time I input a command, it switches to English, so I have to click the Korean/English switching button. 
Which part should I modify to fix this part until I click the Korean/English switching button?

**Comment by scandum** [comment]
To switch to Korean in tintin you'd have to use:
```
#config charset CP949
```
If your system is UTF8 and your mud is CP949, you can use:
```
#config charset CP949TOUTF8
```
If both your system and MUD uses UTF-8, you can use:
```
#config charset UTF-8
```
