### ISSUE TITLE
Values are output instead of keys when using `[]` operator

### ISSUE THREAD

**Issue by zxzxlch** [scandum/tintin#236]
This seems to be a bug. I want to get the keys of a key-value list variable but when I use `x[]`, I get the values instead of the keys.

For example:

```
> #var {x} {{K1}{V1}{K2}{V2}};

> #show $x
{K1}{V1}{K2}{V2}

> #show $x[K1]
V1

> #show $x[]
{V1}{V2}
```

What I expect is to get `{K1}{K2}` instead of `{V1}{V2}`.

---

I'm using [tintin v2.02.41](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/t/tintin.rb) installed from Homebrew.

**Comment by scandum** [comment]
Hi,

You need to use `*x[]` to output the keys.
