### ISSUE TITLE
Mouse tracking issues

### ISSUE THREAD

**Issue by alfuken** [scandum/tintin#31]
OS: Mac OS X
Terminal used: iTerm2
Tintin version: 2.02.05

If you set `#config mouse_tracking on`, it suddenly behaves as if ALL mouse events are being `CATCH`ed and are no longer fired, even if there are no event triggers configured at all — it is no longer possible to select text, scroll in terminal, etc.

If you then set `#config mouse_tracking off` after that, mouse begins to act even more strangely: instead of acting as it supposed to, it begins adding escape codes to client input area:
<img width="1160" alt="Screenshot 2021-02-24 at 10 19 22" src="https://user-images.githubusercontent.com/75377/108978333-c4d7b480-7689-11eb-91c1-11f9f3159932.png">

And at that point only fully restarting the tintin helps fixes this... state.

I was trying to set up `#buffer scroll`ing with mouse, since I use `#split 0 4`

**Comment by scandum** [comment]
With mouse enabled you need to press shift to select text and scroll.

TinTin++ sends "\e[?1000h\e[?1002h\e[?1006h" to enable mouse tracking and "\e[?1000l\e[?1002l\e[?1006l\e[?1016l" to disable mouse tracking.

You may have to file an issue with iTerm2 as this appears to be a bug in iTerm2. Things work fine in xterm.

**Comment by alfuken** [comment]
> With mouse enabled you need to press shift to select text and scroll.

Shouldn't mouse keep behave normally for events that are not prefixed by `CATCH`? Seems like a bug to me. Also, shift+select doesn't work either.

Also, I've tried the same it Mac OS's default terminal application, Terminal.app, it behaves the same way as I described above. 
I've tried different modes, `xterm-256colour`, `xterm-16colour`, `xterm`, `vt100`, `vt102`, `ansi`, no luck.

Though events ARE being generated, `#info events` shows it:
<img width="1153" alt="Screenshot 2021-02-24 at 12 13 10" src="https://user-images.githubusercontent.com/75377/108992585-c4471a00-7699-11eb-97f5-5f01bcf55be8.png">

They're just not being caught by `#event`.

If it doesn't work in the default terminal, then the bug is in the software, not in the terminal.

**Comment by scandum** [comment]
Keep in mind that not every event can be prefixed with CATCH. You'll specifically see a mention of CATCH with #info events enabled.

Mouse mode is a terminal-wide setting, unfortunately you can't pick and choose which mouse events to look for. You may have to press alt/option/fn on OS X to bypass it instead of shift.

I don't have an OS X machine, but since disabling mouse tracking works fine with xterm I do believe it's a bug with iTerm2 / Terminal.

**Comment by alfuken** [comment]
> Mouse mode is a terminal-wide setting
Pity... I guess that renders the whole idea of "#buffer scrolling with #split active" invalid.

What about `#config mouse_tracking off` thingie? Could you reproduce it?

**Comment by scandum** [comment]
I just remembered, #config mouse off was something I broke in 2.02.05 and fixed some months ago. It's fixed in the beta version.

https://mudhalla.net/tintin-beta.tar.gz

**Comment by Lanbosudo** [comment]
> > Mouse mode is a terminal-wide setting
> 
> Pity... I guess that renders the whole idea of "#buffer scrolling with #split active" invalid.
> 
> What about `#config mouse_tracking off` thingie? Could you reproduce it?

Hi alfuken, I'm using [wsltty/mintty](https://github.com/mintty/wsltty) under WSL win 10, and buffer scrolling with split is __doable__ when #enable mouse on. But the same situation happened to me ONCE. I restarted terminal and it was gone.

Yet the #config mouse off thing is the same for me. Maybe I'll try beta if it bothers further.

**Comment by scandum** [comment]
This should be fixed in the latest release.
