### ISSUE TITLE
#break/return not working inside #regexp

### ISSUE THREAD

**Issue by Lanbosudo** [scandum/tintin#37]
Like title says, I found that #break/#return doesn't work as intended when used inside #regexp.
Example: 
```
#foreach {{1}{2}{3}{4}{5}{6}} tmp {
    #regexp {"$tmp"} {"5"} {
        #break;
    } {
        #echo $tmp
    }
}
```
Output is `1 2 3 4 6` instead of `1 2 3 4`.

Is this the way #regexp should be working?

Env: Debian in WSL Windows 10
Tintin: 2.02.05

**Comment by scandum** [comment]
As per #help break
```
The break command can be used inside the #foreach, #loop, #parse,
#while and #switch statements.
```

#regex has its own scope so #break and #return won't work within it.

I'll have to rewrite the scripting engine to handle #regex, which probably won't be anytime soon. You can however use:

```
#foreach {{1}{2}{3}{4}{5}{6}} tmp {
    #regexp {"$tmp"} {"{[^5]."} {
        #echo $tmp
    };
    #else 
    {
        #break;
    }
}
```

**Comment by Lanbosudo** [comment]
> As per #help break
> 
> ```
> The break command can be used inside the #foreach, #loop, #parse,
> #while and #switch statements.
> ```
> 
> #regex has its own scope so #break and #return won't work within it.
> 
> I'll have to rewrite the scripting engine to handle #regex, which probably won't be anytime soon. You can however use:
> 
> ```
> #foreach {{1}{2}{3}{4}{5}{6}} tmp {
>     #regexp {"$tmp"} {"{[^5]}"} {
>         #echo $tmp
>     };
>     #else 
>     {
>         #break;
>     }
> }
> ```

Yeah, sure, that's what i'm doing now. Thanks for the prompt reply~
