### ISSUE TITLE
Variables no longer usable for filenames passed to #history {read} and {write}

### ISSUE THREAD

**Issue by stevensmedia** [scandum/tintin#40]
Hi,

I want to use a different command history for every game I connect to. Thus, I create a filename using `#format`, and then pass that formatted variable to `#history {read} {$worldhistory}` and also to `{write}` on disconnect.

However in 2.02.04, it appears the parsing of #history arguments changed. In prior versions, it used `sub_arg_in_braces` with options of `SUB_VAR|SUB_FUN` to read the second argument of `{read}` and `{write}`, but starting in 2.02.04 it started using `get_arg_in_braces`, removing the handling of variables.

Was this an intentional change?  Or an unintentional regression?

If intentional, is it now intended to be impossible to generate a filename, rather than having it hard-coded?

If unintentional, I ask that `history_read` and `history_write` be modified to use `sub_arg_in_braces` on `arg1`, with the `SUB_VAR|SUB_FUN` options.

Thank you,

**Comment by scandum** [comment]
Hiyas,

Not an intentional regression. I've got it fixed upstream.

You can use `#line sub var #history read $worldhistory` as a workaround.
