### ISSUE TITLE
Undeclared identifier 'environ' in data.c in 2.02.11

### ISSUE THREAD

**Issue by sunpoet** [scandum/tintin#47]
I'm the maintainer of TinTin++ on FreeBSD (net/tintin++). While updating this port to latest 2.02.11, I got the following error:
```
cc -g -Wall  -O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -D_GNU_SOURCE -DHAVE_CONFIG_H -DBIG5   -I/usr/local/include -c data.c
data.c:1346:18: error: use of undeclared identifier 'environ'
                                                for (env = environ ; *env ; env++)
                                                           ^
data.c:1359:18: error: use of undeclared identifier 'environ'
                                                for (env = environ ; *env ; env++)
                                                           ^
2 errors generated.
gmake[1]: *** [Makefile:96: data.o] Error 1
```

**Comment by prool** [comment]
It's the same in macOS Mojave.
I fixed this with the line

extern char **environ;

in beginning of file data.c

**Comment by scandum** [comment]
Thanks, `extern char **environ;` seems to do the trick. I've updated the beta with that fix.

https://mudhalla.net/tintin-beta.tar.gz

**Comment by sunpoet** [comment]
Thank you all. I've updated FreeBSD port to 2.02.11.

**Comment by carlocab** [comment]
By the way, we also need an
```
#include <limits.h>
```
in `scan.c` on macOS (in addition to the change mentioned in https://github.com/scandum/tintin/issues/47#issuecomment-828701145). Otherwise, the build fails with
```
scan.c:324:19: error: use of undeclared identifier 'PATH_MAX'
                if (getcwd(cwd, PATH_MAX) == NULL)
                                ^
```
Build logs available at https://github.com/Homebrew/homebrew-core/actions/runs/855299822.

**Comment by scandum** [comment]
Thanks, updated the beta with a limits.h include as well.

**Comment by scandum** [comment]
https://github.com/scandum/tintin/releases/tag/2.02.12
