### ISSUE TITLE
Tickers queue up during startup session and then don't start upon connection

### ISSUE THREAD

**Issue by atari2600tim** [scandum/tintin#54]
I'm trying to use the script at https://tintin.mudhalla.net/scripts/gmcp.php with 2.02.11, but it appears some kind of behavior changed with tickers between 2.02.05 and 2.02.10, so the status bar part isn't working.

If I start it by giving the file name on the command line on 2.02.05 then the ticker produces error messages until I connect (the screen hasn't split yet, plus it doesn't have the data), which shows that the ticker is running even during the startup session.  Then I connect to game, tell it to send me tailored GMCP message, and it works fine.  I'm not sure if this is the correct behavior or not because the help for tickers in .05 also says that they did not run during the startup session back then either.

If I do the same thing with 2.02.11, the status bar doesn't run even after connecting.  I am able to get it to start working if I manually start a second ticker.

Then as a troubleshooting step removing whatever complexity of the gmcp and map and all that, I tried just starting the program without the script and just pasting 2 lines in...
* `#TICKER {demo1} { #line ignore #showme {demo1} } {1}`
* (wait a few seconds)
* (start session)
* (wait a little)
*  `#TICKER {demo2} { #line ignore #showme {demo2} } {1}`.

On old version (2.02.05), it gives me "demo1" every second starting when I typed it even though I'm in the startup session.  On new version (2.02.11 or .10), it gives me neither message until I start the demo2 ticker, at that point it gives me a bunch of demo1 messages and a few demo2 messages, around 10:1 and then become 1:1 alternating after a while.  I assume this means that the demo1 ticks were queued up during the time that I was in the startup session and the time after I connected but before starting the second ticker, but only started happening once creating the second ticker got it going.

**Comment by scandum** [comment]
Thanks, thought I fixed that problem, but clearly I didn't. I'll look into it.

**Comment by scandum** [comment]
Alright, this should be fixed in the beta. https://mudhalla.net/tintin-beta.tar.gz

**Comment by atari2600tim** [comment]
Looks good
