### ISSUE TITLE
Variable containing { in #if clause causes unmatched brace

### ISSUE THREAD

**Issue by rigrig** [scandum/tintin#56]
Using TinTin 2.02.12b, I'm trying to filter key presses, but now typing `{` causes an error.

Debug log of
1. setting up `#event {RECEIVED KEYPRESS} { #if {"%0" === " "} {#showme space}}`, 
2. pressing `spacebar` and 
3. pressing `{`:
```
#event {RECEIVED KEYPRESS} { #if {"%0" === " "} {#showme space}}
    #event {RECEIVED KEYPRESS} { #if {"%0" === " "} {#showme space}}
#EVENT {RECEIVED KEYPRESS} HAS BEEN SET TO { #if {"%0" === " "} {#showme space}}.
#DEBUG EVENT {RECEIVED KEYPRESS} { #if {"%0" === " "} {#showme space}}
    #if {" " === " "}
        #showme space
space
    #endif
 #DEBUG EVENT {RECEIVED KEYPRESS} { #if {"%0" === " "} {#showme space}}
#ERROR: GET BRACED ARGUMENT: UNMATCHED BRACE.
    #if {"{" === " "} {#showme space}}
#MATH EXP: UNKNOWN OPERATOR: }
    #endif
{
```
(Using braces instead of quotes  made no difference: `#event {RECEIVED KEYPRESS} { #if {{%0} === {}} {#showme space}}`)

### Workaround:
Filtering by unicode index (`%1`) instead works.

**Comment by scandum** [comment]
Thanks, I made a note on my todo list. Using %1 is probably the easiest solution regardless.

You can use #echo %A {<character>} to get the decimal unicode index in-client.

**Comment by scandum** [comment]
Fixed in https://github.com/scandum/tintin/releases/tag/2.02.12 where { } gets turned into a \x code.
