### ISSUE TITLE
#SSL ALERT not printing filename

### ISSUE THREAD

**Issue by nyankers** [scandum/tintin#62]
Hi,

If you try to connect via #SSL and the remote server's certificate changed, you can get a message like this:
```
#SSL ERROR: SERVER CERTIFICATE IS DIFFERENT FROM THE SAVED ONE.
#SSL ALERT: THE SERVER'S SETTINGS WERE CHANGED IN AN UNEXPECTED WAY.
#SSL ALERT: YOU MAY BE VULNERABLE TO MAN-IN-THE-MIDDLE ATTACKS.
#SSL ALERT: TO CONTINUE, PLEASE DELETE THE FILE:
#SSL ALERT: 
#SSL ERROR: ABORTING CONNECTION.
```

The trouble is that the last #SSL ALERT line is supposed to print the filename, but instead prints RAM garbage because the filename is not actually captured for this message.

This is the `filename` variable in `ssl.c` function `ssl_check_cert()`.

Though perhaps not the most elegant solution (as the filename is already gathered in another function call within this one), it can nevertheless be resolved by adding `get_cert_file(ses, filename);` before the `filename` variable is used. Another solution might be to pass the `filename` buffer to that other function and have it use that instead of its own local buffer, but this is a rare enough error that I went with the first one locally.

**Comment by scandum** [comment]
Thanks, added it to my todo list.

**Comment by scandum** [comment]
This should be fixed in the beta, seems indeed like a simple case of adding `get_cert_file(ses, filename);`

**Comment by scandum** [comment]
https://github.com/scandum/tintin/releases/tag/2.02.12
