### ISSUE TITLE
Disable semicolon command stringing outside of tintin commands

### ISSUE THREAD

**Issue by BeeFox-sys** [scandum/tintin#63]
when typing a semicolon outside of a tintin command, it is interpreted as a command split, however many mushes also use ; as a command split, and while you can escape it to send it to the server, there should be a way to disable it in messages sent to the server

**Comment by scandum** [comment]
You can use `#config verbatim on` to disable command splitting for manual input.

**Comment by BeeFox-sys** [comment]
thank you!
