### ISSUE TITLE
 Extra leading whitespace in Charset accepted/rejected

### ISSUE THREAD

**Issue by nschimme** [scandum/tintin#83]
TinTin++ has a bug and adds a leading space in the accepted or rejected message: " UTF-8" rather than "UTF-8"

https://github.com/scandum/tintin/blob/b0fa43339e199bfdfced35b97e92d85d31287be9/src/telopt_client.c#L1391-L1401

Solution seems to be changing `"%c%c%c%c %s%c%c"` to `"%c%c%c%c%s%c%c"`

**Comment by scandum** [comment]
Thanks, should be fixed in the beta. https://mudhalla.net/tintin-beta.tar.gz

**Comment by nschimme** [comment]
Works, thanks!
